server:
  port: 80

spring:
  application:
    name: consul-consumer-payment
  cloud:
    consul:  # 注册中心配置
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}